# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonce',
            name='redirect_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='openiduser',
            name='access_token',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='openiduser',
            name='refresh_token',
            field=models.CharField(max_length=1000),
        ),
    ]
